### ISSUE TITLE
Why not have test.py or visualization.py

### ISSUE THREAD

**Issue by qiuhaining** [antabangun/DualRefine#1]
I want to test my image and visualize ego-motion, but lack of related codes

**Comment by antabangun** [comment]
Thank you for your interest in our work. I've updated the repo to include `demo.py`, which you can run on the downloaded KITTI dataset as follows:
```bash
python demo.py --load_weights_folder weights/DualRefine_MR
```
It will visualize the input image and estimated depths.

If you want to test on your own images, you can follow the codes in `demo.py`. But essentially you would need to input sequence of images and also the intrinsics calibration parameters into the model.

**Comment by qiuhaining** [comment]
> 
It means if the intrinsics is different, i need train the model with the new intrinsics ???

**Comment by antabangun** [comment]
No. The intrinsics are only needed to compute two-view geometry; you can just use the pre-trained weights.

The network itself mostly behaves similarly to previous works, so do note that it will have the same generalization issues as previous works if the appearance/domain of your images highly differs from the training data.
In that case, you can try training it on your data using the self-supervision trainer code.

**Comment by qiuhaining** [comment]
> No. The intrinsics are only needed to compute two-view geometry; you can just use the pre-trained weights.
> 
> The network itself mostly behaves similarly to previous works, so do note that it will have the same generalization issues as previous works if the appearance/domain of your images highly differs from the training data. In that case, you can try training it on your data using the self-supervision trainer code.



> No. The intrinsics are only needed to compute two-view geometry; you can just use the pre-trained weights.
> 
> The network itself mostly behaves similarly to previous works, so do note that it will have the same generalization issues as previous works if the appearance/domain of your images highly differs from the training data. In that case, you can try training it on your data using the self-supervision trainer code.

I found the paper：https://arxiv.org/pdf/2110.14347.pdf， with Unknown Camera
Parameters，what do you think about it？

**Comment by antabangun** [comment]
This line of research is excellent. as it focuses on training using large datasets with unknown intrinsic by having the network learn it automatically. If you don't know the intrinsic of your dataset of interest, then modifying the training code to implement the intrinsic estimation head as described in the paper could work. But then, you would need to re-train the model with your dataset or, preferably, with multiple datasets, to generalize to varying camera intrinsics. If it is possible to perform camera calibration manually, it would be preferable to do that as it would likely be more accurate.
