### ISSUE TITLE
About Separating the Pose Network

### ISSUE THREAD

**Issue by wangjiyuan9** [antabangun/DualRefine#6]
Dear Author,

Thank you for your outstanding work. I am currently very interested in extracting the precise pose network from your model and fixing its parameters to train other models. Could you please advise on how to achieve this?

Best regards,
WJY

**Comment by antabangun** [comment]
Thank you for your interest.
The refinement module of DualRefine refines both the pose and depth estimates in an alternating fashion. Both estimates rely on the improvement of the other, so unfortunately it will be difficult to extract only the pose network.

**Comment by wangjiyuan9** [comment]
Thank you for your quick reply!!!
