### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by wangjiyuan9** [antabangun/DualRefine#8]
Thank you for your amazing work!
 I've read your paper twice times and I believe there are some questions that  most people will have:
1. The 'F', is really confusing as it never introduces them in paper
![image](https://github.com/user-attachments/assets/b62fbc0c-c5a0-4e8c-8d41-845321f3ff49)
![image](https://github.com/user-attachments/assets/6f3433dc-6bb4-4820-9e8c-215db45814d1)
2. Why always use Resnet 18 as the pose encoder? Will it be better with Resnet 50 or ViT? Is there any experiment to prove that?
3. The cost map C_k has:
![image](https://github.com/user-attachments/assets/251246a0-f787-4817-bddc-b21476df6758)
But you say there is such a number of candidates:
![image](https://github.com/user-attachments/assets/a43f2726-26f6-422c-b24a-53cf78e4542d)
I believe there must be some details or logistics I ignored because you use 'c' here:
![image](https://github.com/user-attachments/assets/39a2df7b-fc32-4d20-8819-5900069a355f)
Could you please give me an explanation? Really thank you!

**Comment by antabangun** [comment]
Thank you for pointing out unclear points which could have been written better.
1. `F` are feature maps from multiple stages/scales, as mentioned in the line from the second image.
2. We tried Resnet50 as pose network but I don't remember the conclusion we made and didn't explore this in detail to stay consistent with previous works. Experimenting with various pose networks is an interesting idea though, and perhaps its something you could explore.
3. `c=D[u]/C` is defined in that paragraph. 
The candidates are the following set: `{D[u] + (i x c x n) | i=[-r,-r+1,...,r-1,r], c=D[u]/C, n=[1,2,3] }`. So in total `n x (2 x r + 1)` candidates.

**Comment by wangjiyuan9** [comment]
Thank you for your valuable explanation!
